---
trainingInput:
    scaleTier: CUSTOM
    # Configure a master worker with 2 T4 GPUs
    masterType: n1-highcpu-16
    masterConfig:
        acceleratorConfig:
            count: 2
            type: NVIDIA_TESLA_T4
    # Configure 1 worker, with 4 T4 GPUs
    workerCount: 1
    workerType: n1-highcpu-16
    workerConfig:
        acceleratorConfig:
            count: 4
            type: NVIDIA_TESLA_T4
    # Configure 1 parameter server with no GPUs
    parameterServerCount: 1
    parameterServerType: n1-highmem-8
