feature {
  name: "synopsis"
  type: BYTES
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "tags"
  value_count {
    min: 1
  }
  type: BYTES
  string_domain {
    value: "Bobsledding"
    value: "Dog sled"
    value: "Funk Music"
    value: "Men\'s Individual - Large Hill"
    value: "Women\'s Singles"
    value: "Men\'s Snowboard Cross"
    value: "Episode"
    value: "Horse"
    value: "Hunting"
    value: "Pro Wrestling"
    value: "Men\'s Team Sprint Freestyle"
    value: "Ski Jumping"
    value: "Nordic combined"
    value: "Auto Racing"
    value: "Game Show"
    value: "Reggae Music"
    value: "Gaming"
    value: "Bullfighting"
    value: "Movie"
    value: "Curling"
    value: "Women\'s 500m"
    value: "Mixed Ice Dance"
    value: "Arts & Literature"
    value: "Ancient history"
    value: "Soul Music"
    value: "Animated Comedy"
    value: "Open Double"
    value: "Local"
    value: "Fantasy"
    value: "Docudrama"
    value: "Anthology"
    value: "Opera"
    value: "Judo"
    value: "Short track speed skating"
    value: "Women\'s 3000m Relay"
    value: "Women\'s Parallel Giant Slalom"
    value: "Entertainment"
    value: "Hip-Hop & Rap Music"
    value: "Western"
    value: "Filmreihe"
    value: "eSports"
    value: "Lacrosse"
    value: "Field Hockey"
    value: "Yom Kippur"
    value: "Kom\303\266die"
    value: "Men\'s 12.5km Pursuit"
    value: "Men\'s 4 x 7.5km Relay"
    value: "Variety"
    value: "Basketball"
    value: "Biathlon"
    value: "Men\'s Individual"
    value: "Men\'s Alpine Combined"
    value: "Sports"
    value: "Motorcycle"
    value: "Water Polo"
    value: "Women\'s Slopestyle"
    value: "Men\'s 10000m"
    value: "Men\'s Super G"
    value: "Agriculture"
    value: "Musical comedy"
    value: "Boat"
    value: "Folk Music"
    value: "Rio 2016"
    value: "Cross-Country Skiing"
    value: "Retrospective"
    value: "Crime drama"
    value: "Educational"
    value: "Teens"
    value: "Horror"
    value: "Collectibles"
    value: "Billiards"
    value: "Dog Show"
    value: "Karaoke"
    value: "Table Tennis"
    value: "Men\'s 4 x 10km Relay"
    value: "Men\'s Moguls"
    value: "Horse Racing"
    value: "Shooting"
    value: "Men\'s 2-Man Competition"
    value: "Drift racing"
    value: "Newsmagazine"
    value: "Documentary"
    value: "older teens (ages 15+)"
    value: "Auction"
    value: "Triathlon"
    value: "Based on the Video Game"
    value: "Amazon Original"
    value: "Australian Football"
    value: "Women\'s 10km Freestyle"
    value: "Men\'s Mass Start 16 Laps"
    value: "Crime"
    value: "Animated"
    value: "Public Affairs"
    value: "teens (ages 13-14)"
    value: "Motorcycle Racing"
    value: "Diving"
    value: "History drama"
    value: "Beach soccer"
    value: "Women\'s Moguls"
    value: "Nordic Combined"
    value: "Business & Finance"
    value: "Thriller"
    value: "Fitness"
    value: "World Music"
    value: "Blues Music"
    value: "Dog Racing"
    value: "Highlights"
    value: "Science & Technology"
    value: "Debate"
    value: "Ringuette"
    value: "Labor Day"
    value: "Hockey"
    value: "Home & Garden"
    value: "Standup"
    value: "Performing arts"
    value: "Easter"
    value: "Ballet"
    value: "Classic Movies"
    value: "Women\'s 5000m"
    value: "Water Skiing"
    value: "Ice Skating"
    value: "Women\'s Aerials"
    value: "Men\'s Curling"
    value: "Bowls"
    value: "Women\'s Ski Cross"
    value: "Music"
    value: "Romance"
    value: "Family Entertainment"
    value: "Men\'s Single"
    value: "Blackjack"
    value: "Women\'s Downhill"
    value: "not for kids"
    value: "Fishing"
    value: "2018 World Cup"
    value: "Valentine\'s Day"
    value: "Halloween"
    value: "Bull riding"
    value: "Canada Day"
    value: "Women\'s Snowboard Cross"
    value: "spa"
    value: "Legal"
    value: "R&B Music"
    value: "Consumer"
    value: "Men\'s Gundersen Large Hill / 10km"
    value: "Mixed Team - Relay"
    value: "Women\'s Mass Start 16 Laps"
    value: "Medical"
    value: "Action & Adventure"
    value: "Environment"
    value: "American history"
    value: "Skateboarding"
    value: "Roller derby"
    value: "Men\'s Downhill"
    value: "eng"
    value: "History"
    value: "Pop Music"
    value: "Soap Opera"
    value: "Crafts"
    value: "Boating"
    value: "Snowmobiling"
    value: "Women\'s Ice Hockey"
    value: "Classic Sport Event"
    value: "Darts"
    value: "Men\'s Team Large Hill / 4 x 5km"
    value: "Motor Sports"
    value: "Techno Music"
    value: "Track & Field"
    value: "Playoffs"
    value: "Rowing"
    value: "Mixed Team"
    value: "Women\'s Sprint Classic Style"
    value: "Classic Sports"
    value: "Men\'s 15km Mass Start"
    value: "Self improvement"
    value: "Fashion"
    value: "Romantic comedy"
    value: "Newscast"
    value: "Paranormal"
    value: "Weddings"
    value: "Card Games"
    value: "Independent"
    value: "Women\'s 2 x 7.5km Skiathlon"
    value: "Men\'s Slalom"
    value: "4K Test Tag"
    value: "Comedy"
    value: "Comedy drama"
    value: "Volleyball"
    value: "Cycling"
    value: "Sailing"
    value: "Rhythmic Gymnastics"
    value: "Women\'s 15km Individual"
    value: "Teleroman"
    value: "Soccer"
    value: "Historical drama"
    value: "Dark comedy"
    value: "Christmas"
    value: "Awards"
    value: "Art de Vivre"
    value: "Men\'s 5000m"
    value: "Women\'s 10km Pursuit"
    value: "Profile"
    value: "Men\'s 5000m Relay"
    value: "Gaelic Football"
    value: "Women\'s Individual - Normal Hill"
    value: "Miniseries"
    value: "Science fiction"
    value: "Martial arts"
    value: "Preschool"
    value: "Wrestling"
    value: "Modern Pentathlon"
    value: "Mixed Pairs"
    value: "Freestyle Skiing"
    value: "Women\'s Super G"
    value: "Interview"
    value: "Yacht Racing"
    value: "Aerobics"
    value: "Latin Music"
    value: "Snooker"
    value: "Bicycle racing"
    value: "Multi-sport event"
    value: "Boxing Day"
    value: "Women\'s 7.5km Sprint"
    value: "Floorball"
    value: "Sports non-event"
    value: "Sitcom"
    value: "Country Music"
    value: "Real Estate"
    value: "Shopping"
    value: "Anime"
    value: "Bodybuilding"
    value: "Romance comedy"
    value: "Hurling"
    value: "Canoeing"
    value: "Cinco de Mayo"
    value: "Intl soccer"
    value: "Trampoline Gymnastics"
    value: "New Year\'s"
    value: "Magazine"
    value: "Men\'s Team - Large Hill"
    value: "Spin-Off"
    value: "Travel"
    value: "Golf"
    value: "Handball"
    value: "Men\'s Slopestyle"
    value: "20 de noviembre"
    value: "Women\'s Giant Slalom"
    value: "Short Subject"
    value: "Behind the Scenes"
    value: "kids (ages 5-9)"
    value: "Heavy Metal Music"
    value: "Dance"
    value: "Poker"
    value: "Cheerleading"
    value: "Racquetball"
    value: "Men\'s Singles"
    value: "Men\'s 1500m"
    value: "Current Affairs"
    value: "Boxing"
    value: "SportingEvent"
    value: "Theater"
    value: "Women\'s 30km Classic Style"
    value: "Men\'s Sprint Classic Style"
    value: "Politics & Government"
    value: "Surfing"
    value: "Rugby union"
    value: "Quebec Production"
    value: "Serial"
    value: "Women\'s Halfpipe"
    value: "Reality Competition"
    value: "Indoor soccer"
    value: "Mixed Martial Arts"
    value: "Aviation"
    value: "Weightlifting"
    value: "PyeongChang 2018"
    value: "Pool"
    value: "Beach Volleyball"
    value: "Badminton"
    value: "Easy Listening Music"
    value: "Rugby league"
    value: "Men\'s 10km Sprint"
    value: "Women\'s 12.5km Mass Start"
    value: "Women\'s 1500m"
    value: "Food"
    value: "Talk"
    value: "Fundraiser/Telethon"
    value: "Arm Wrestling"
    value: "Thanksgiving"
    value: "Jazz Music"
    value: "Men\'s Team Pursuit 8 Laps"
    value: "Dokusoap"
    value: "Auto"
    value: "Art"
    value: "Home improvement"
    value: "Bluegrass Music"
    value: "Wall Street"
    value: "Netflix Original"
    value: "Taekwondo"
    value: "Goth Music"
    value: "Mixed 2 x 6 + 2 x 7.5km Relay"
    value: "Mystery"
    value: "Swimming"
    value: "Foreign"
    value: "World history"
    value: "Squash"
    value: "Footvolley"
    value: "St. Patrick\'s Day"
    value: "Women\'s Single"
    value: "Women\'s Team Pursuit 6 Laps"
    value: "Soft Rock"
    value: "Women\'s 3000m"
    value: "Military & War"
    value: "Summer Olympics"
    value: "Courtroom"
    value: "Parade"
    value: "Alternative Music"
    value: "Luge"
    value: "Men\'s Gundersen Normal Hill / 10km"
    value: "Lifestyle"
    value: "Cooking"
    value: "Computers"
    value: "Rock Music"
    value: "Sumo Wrestling"
    value: "Synchronized Swimming"
    value: "Sequel"
    value: "Men\'s 2 x 15km Skiathlon"
    value: "Mex. Independence"
    value: "Investigative"
    value: "Men\'s 20km Individual"
    value: "Health"
    value: "Rugby"
    value: "Women\'s Big Air"
    value: "Biography"
    value: "Softball"
    value: "Adaptation"
    value: "Women\'s Slalom"
    value: "Religion"
    value: "Animals"
    value: "Archery"
    value: "Musical"
    value: "Classical Music"
    value: "Men\'s Halfpipe"
    value: "Men\'s 15km Freestyle"
    value: "Women\'s 4 x 5km Relay"
    value: "Women\'s Individual"
    value: "Coming of Age"
    value: "Men\'s Parallel Giant Slalom"
    value: "Parenting"
    value: "Olympics"
    value: "Winter Olympics"
    value: "Marathon"
    value: "Advice"
    value: "Bollywood"
    value: "Dating"
    value: "Men\'s 1000m"
    value: "Women\'s Team Sprint Freestyle"
    value: "Men\'s Giant Slalom"
    value: "Men\'s 500m"
    value: "News"
    value: "Outdoors"
    value: "tweens (ages 10-12)"
    value: "Cricket"
    value: "Gospel Music"
    value: "Mixed Curling"
    value: "Cartoon"
    value: "Men\'s Big Air"
    value: "Erotic"
    value: "Special"
    value: "Action Sports"
    value: "Speedskating"
    value: "Figure Skating"
    value: "Holiday"
    value: "Drag Racing"
    value: "Police"
    value: "Women\'s Alpine Combined"
    value: "Reality"
    value: "preschoolers (ages 2-4)"
    value: "Pets"
    value: "Football"
    value: "Baseball"
    value: "Polo"
    value: "Snowboarding"
    value: "Bicycle"
    value: "Kayaking"
    value: "Men\'s Aerials"
    value: "Music Video"
    value: "Women\'s 4 x 6km Relay"
    value: "Drama"
    value: "Weather"
    value: "Gay and Lesbian"
    value: "Skiing"
    value: "Fencing"
    value: "Women\'s Curling"
    value: "Pro"
    value: "Women\'s 1000m"
    value: "Hydroplane racing"
    value: "Nature"
    value: "Tennis"
    value: "Alpine Skiing"
    value: "Men\'s Ice Hockey"
    value: "Hanukkah"
    value: "Men\'s Individual - Normal Hill"
    value: "Senior Citizen"
    value: "Water Sports"
    value: "Concert"
    value: "Running"
    value: "Women\'s 2-Man Competition"
    value: "Men\'s 50km Classic Style"
    value: "Trains"
    value: "Open 4-Man Competition"
    value: "Men\'s Ski Cross"
    value: "Skeleton"
    value: "Children\'s/Family Entertainment"
    value: "Equestrian"
    value: "Event"
    value: "Mountain Biking"
    value: "Gymnastics"
    value: "Pelota vasca"
    value: "Sports talk"
    value: "How-To"
    value: "Suspense"
    value: "Rodeo"
    value: "Documentary drama"
    value: "Bowling"
    value: "July 4th"
    value: "Ska Music"
  }
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  distribution_constraints {
    min_domain_mass: 0.95
  }
  drift_comparator {
    infinity_norm {
      threshold: 0.05
    }
  }
}
