feature {
  name: "synopsis"
  type: BYTES
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "tags"
  value_count {
    min: 1
  }
  type: BYTES
  string_domain {
    value: "Art"
    value: "Movie"
    value: "eng"
    value: "Documentary"
    value: "spa"
    value: "Special"
    value: "Entertainment"
    value: "News"
    value: "Anime"
    value: "Comedy"
    value: "Fantasy"
    value: "Martial arts"
    value: "Action & Adventure"
    value: "Science fiction"
    value: "Animated"
    value: "teens (ages 13-14)"
    value: "Netflix Original"
    value: "Drama"
    value: "tweens (ages 10-12)"
    value: "Crime"
    value: "Mystery"
    value: "Thriller"
    value: "Crime drama"
    value: "History drama"
    value: "Western"
    value: "Teens"
    value: "Independent"
    value: "older teens (ages 15+)"
    value: "Romance"
    value: "Suspense"
    value: "Horror"
    value: "Foreign"
    value: "Comedy drama"
    value: "Gay and Lesbian"
    value: "Miniseries"
    value: "History"
    value: "Biography"
    value: "Courtroom"
    value: "Music"
    value: "Musical"
    value: "Military & War"
    value: "Holiday"
    value: "Romance comedy"
    value: "New Year's"
    value: "Christmas"
    value: "Children's/Family Entertainment"
    value: "Religion"
    value: "Weddings"
    value: "Bollywood"
    value: "Documentary drama"
    value: "kids (ages 5-9)"
    value: "Quebec Production"
    value: "Halloween"
    value: "Based on the Video Game"
    value: "Sports"
    value: "Dark comedy"
    value: "Easter"
    value: "not for kids"
    value: "Classic Movies"
    value: "Amazon Original"
    value: "Theater"
    value: "Latin Music"
    value: "Educational"
    value: "Paranormal"
    value: "Musical comedy"
    value: "Local"
    value: "Standup"
    value: "Pop Music"
    value: "Rock Music"
    value: "Jazz Music"
    value: "Classical Music"
    value: "Thanksgiving"
    value: "Nature"
    value: "Soccer"
    value: "Sports non-event"
    value: "Concert"
    value: "preschoolers (ages 2-4)"
    value: "Valentine's Day"
    value: "Wall Street"
    value: "Health"
    value: "Travel"
    value: "Pro Wrestling"
    value: "Animals"
    value: "Alternative Music"
    value: "Advice"
    value: "Politics & Government"
    value: "Hip-Hop & Rap Music"
    value: "Country Music"
    value: "Performing arts"
    value: "Preschool"
    value: "Reality"
    value: "Interview"
    value: "Dance"
    value: "Science & Technology"
    value: "Folk Music"
    value: "Soul Music"
    value: "Heavy Metal Music"
    value: "Gospel Music"
    value: "R&B Music"
    value: "Blues Music"
    value: "Episode"
    value: "Anthology"
    value: "Talk"
    value: "How-To"
    value: "Public Affairs"
    value: "Variety"
    value: "Crafts"
    value: "Newsmagazine"
    value: "Shopping"
    value: "Fashion"
    value: "Docudrama"
    value: "Home & Garden"
    value: "Business & Finance"
    value: "Auto"
    value: "Food"
    value: "Golf"
    value: "Newscast"
    value: "Legal"
    value: "Soap Opera"
    value: "Historical drama"
    value: "Football"
    value: "Mixed Martial Arts"
    value: "Sitcom"
    value: "Hockey"
    value: "SportingEvent"
    value: "Classic Sport Event"
    value: "Home improvement"
    value: "Sports talk"
    value: "Auto Racing"
    value: "Action Sports"
    value: "Fishing"
    value: "Basketball"
    value: "Tennis"
    value: "Game Show"
    value: "Medical"
    value: "Baseball"
    value: "Consumer"
    value: "Computers"
    value: "Outdoors"
    value: "Fitness"
    value: "Hunting"
    value: "Real Estate"
    value: "Parenting"
    value: "Boxing"
    value: "Agriculture"
    value: "Olympics"
    value: "Erotic"
  }
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  distribution_constraints {
    min_domain_mass: 0.95
  }
  drift_comparator {
    infinity_norm {
      threshold: 0.05
    }
  }
}
